apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.app.korotin.dev
spec:
  group: app.korotin.dev
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Application is the Schema for the applications API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ApplicationSpec defines the desired state of Application
          properties:
            containers:
              items:
                description: ApplicationContainer defines specific container in application
                properties:
                  cpuLimit:
                    maxLength: 15
                    minLength: 1
                    type: string
                  image:
                    minLength: 1
                    type: string
                  memoryLimit:
                    maxLength: 15
                    minLength: 1
                    type: string
                  name:
                    minLength: 1
                    type: string
                  ports:
                    items:
                      properties:
                        containerPort:
                          format: int32
                          maximum: 65535
                          minimum: 1
                          type: integer
                        hostPort:
                          format: int32
                          maximum: 65535
                          minimum: 1
                          type: integer
                        name:
                          maxLength: 15
                          minLength: 1
                          type: string
                      required:
                      - containerPort
                      - hostPort
                      - name
                      type: object
                    minItems: 1
                    type: array
                required:
                - cpuLimit
                - image
                - memoryLimit
                - name
                - ports
                type: object
              minItems: 1
              type: array
            replicas:
              format: int32
              minimum: 0
              type: integer
          required:
          - containers
          - replicas
          type: object
        status:
          description: ApplicationStatus defines the observed state of Application
          properties:
            pods:
              items:
                type: string
              type: array
            replicas:
              format: int32
              type: integer
          required:
          - pods
          - replicas
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
